-- system usage and billing

use role accountadmin;

SELECT 
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS TOTAL_CREDIT_USED,
    SUM(CREDITS_USED_COMPUTE) AS TOTAL_WAREHOUSE_CREDIT_USED,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS
    TOTAL_CREDITS_USED_CLOUD_SERVICES
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY 1;

SELECT 
    USAGE_DATE,
    SERVICE_TYPE,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS
    CREDITS_USED_CLOUD_SERVICES,
    SUM(CREDITS_USED) AS TOTAL_CREDITS_USED,
    SUM(CREDITS_ADJUSTMENT_CLOUD_SERVICES) AS
    CREDITS_ADJUSTMENT_CLOUD_SERVICES,
    SUM(CREDITS_BILLED) AS CREDITS_BILLED
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
GROUP BY 1,2
ORDER BY USAGE_DATE DESC;

-- views from Information schema 
use database demo_data_loading;
SELECT *
FROM
TABLE(INFORMATION_SCHEMA.WAREHOUSE_METERING_HISTORY(DATEADD('DAYS',-10,current_date)));


SELECT 
    USAGE_DATE,
    DATABASE_ID,
    DATABASE_NAME,
    DELETED,
    AVERAGE_DATABASE_BYTES /1024 / 1024 AS AVERAGE_DATABASE_MB,
    AVERAGE_FAILSAFE_BYTES / 1024 / 1024 AS AVERAGE_FAILSAFE_MB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE DATABASE_NAME = 'DEMO_DATA_LOADING'
ORDER BY USAGE_DATE DESC;

SELECT 
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    ACTIVE_BYTES / 1024 / 1024 AS ACTIVE_BYTES_MB,
    TIME_TRAVEL_BYTES / 1024 / 1024 AS TIME_TRAVEL_BYTES_MB,
    FAILSAFE_BYTES / 1024 / 1024 AS FAILSAFE_BYTES_MB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG = 'DEMO_DATA_LOADING';

SELECT 
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    ACTIVE_BYTES / 1024 / 1024 AS ACTIVE_BYTES_MB,
    TIME_TRAVEL_BYTES / 1024 / 1024 AS TIME_TRAVEL_BYTES_MB,
    FAILSAFE_BYTES / 1024 / 1024 AS FAILSAFE_BYTES_MB
FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
WHERE TABLE_CATALOG IN ('DEMO_DATA_LOADING','TEST_CLONING');